### ISSUE TITLE
The 'micro' configuration doesn't really generate the SMALLEST size?

### ISSUE THREAD

**Issue by guotata1996** [mwydmuch/PyOblige#2]
I tried the first three configurations and found the size of the generated maps:
micro ≈ tiny > small
But literally micro means the smallest, doesn't it ?

**Comment by guotata1996** [comment]
Sorry that I forgot to mention my platform is windows.. so is this feature not supported on windows?

**Comment by mwydmuch** [comment]
Hello @guotata1996,
version that is available to download from releases site should also support additional map sizes.
